In [1]:
import pandas as pd
from cell_cycle_gating import manual_gating as mg
from cell_cycle_gating import dead_cell_filter_ldrint as dcf_int
import matplotlib
import numpy as np
import matplotlib.pyplot as plt

In [2]:
### define channel names and well/file to be updated

#well = 'K04' ## bad well
well = 'K03' ## good well

#obj = "/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78/210423_combo_78.result."+well+"[test].csv"
obj = "/Volumes/hits/lsp-analysis/LINCS-combinations/rep8/210423_combo_78/210423_combo_78.result."+well+"[test].csv"

ndict = {'Well Name':'well',
         'ldrint': 'ldr',
        'Cell: DNAcontent (DD-bckgrnd)': 'dna'
        }


In [3]:
well = 'K03'
f = "210423_combo_78.result."+well+"[test].csv"
#batch = "/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78"
batch = "/Volumes/hits/lsp-analysis/LINCS-combinations/rep8/210423_combo_78"
dcf_int.get_counts(batch=batch, filename=f, ndict = ndict, is_csv=True)

[      -inf 3.50939971]


/Users/nickclark/miniforge3/lib/python3.10/site-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)


barcode well  alive  alive_subg1  \
0  /Volumes/hits/lsp-analysis/LINCS-combinations/...  K03   1536           22   

   alive_beyondg2  dead_ldrpos  dead_subg1  cell_count  cell_count__dead  \
0              58           64          18        1616                82   

   cell_count__total  
0               1698

In [4]:
well = 'K04'
f = "210423_combo_78.result."+well+"[test].csv"
#batch = "/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78"
batch = "/Volumes/hits/lsp-analysis/LINCS-combinations/rep8/210423_combo_78"
dcf_int.get_counts(batch=batch, filename=f, ndict = ndict, is_csv=True)
### testing with higher peak_loc value (default was 1.2)
#dcf_int.get_counts(batch="/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78", filename=f, ndict = ndict, is_csv=True, peak_loc = 2)

[      -inf 1.33234865]


/Users/nickclark/miniforge3/lib/python3.10/site-packages/pandas/core/arraylike.py:402: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)


barcode well  alive  alive_subg1  \
0  /Volumes/hits/lsp-analysis/LINCS-combinations/...  K04    101            7   

   alive_beyondg2  dead_ldrpos  dead_subg1  cell_count  cell_count__dead  \
0               3         1476          12         111              1488   

   cell_count__total  
0               1599

In [5]:
well = "K03"
#obj = "/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78/210423_combo_78.result."+well+"[test].csv"
obj = "/Volumes/hits/lsp-analysis/LINCS-combinations/rep8/210423_combo_78/210423_combo_78.result."+well+"[test].csv"

y = mg.update_ldr_gating(obj, well, ndict, plot_ldr_log10=True, plot_with_dna = True, is_ldrint = True, is_csv=True)
display(y)

/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:244: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:102: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:151: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:319: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)


interactive(children=(FloatSlider(value=3.5093997105083767, description='ldr_cutoff', max=4.361394611425605, m…

In [6]:
well = "K04"
obj = "/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78/210423_combo_78.result."+well+"[test].csv"
obj = "/Volumes/hits/lsp-analysis/LINCS-combinations/rep8/210423_combo_78/210423_combo_78.result."+well+"[test].csv"
y1 = mg.update_ldr_gating(obj, well, ndict, plot_ldr_log10=True, plot_with_dna = True, is_ldrint = True, is_csv=True)
display(y1)

/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:244: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:102: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:151: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/Users/nickclark/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:319: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)


interactive(children=(FloatSlider(value=1.3323486469448813, description='ldr_cutoff', max=4.365333849998564, m…

In [8]:
well = 'K04'
f = "210423_combo_78.result."+well+"[test].csv"
#dcf_int.get_counts(batch="/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78", filename=f, ndict = ndict, is_csv=True)
### testing with higher peak_loc value (default was 1.2)
dcf_int.get_counts(batch="/mnt/y/lsp-analysis/LINCS-combinations/rep8/210423_combo_78", filename=f, ndict = ndict, is_csv=True, peak_loc = 2)

peak_locs
[ 22  43  64 151]
cc
[0.29697258 0.81466061 1.33234865 3.47705621]
[      -inf 3.47705621]


/home/nick/mambaforge/lib/python3.10/site-packages/pandas/core/arraylike.py:396: RuntimeWarning: invalid value encountered in log10
  result = getattr(ufunc, method)(*inputs, **kwargs)


barcode well  alive  alive_subg1  \
0  /mnt/y/lsp-analysis/LINCS-combinations/rep8/21...  K04   1415           24   

   alive_beyondg2  dead_ldrpos  dead_subg1  cell_count  cell_count__dead  \
0              86           56          18        1525                74   

   cell_count__total  
0               1599

In [31]:
### look at 2021-10-05 SUM1315 -- high dead counts on end-time controls -- e.g. plate 160
well = "H07"
obj = "/mnt/y/lsp-analysis/LINCS-combinations/redo_rep1_and_2/211005_combo_160/211005_combo_160.result."+well+"[test].csv"
ndict = {'Well Name':'well',
         'ldrint': 'ldr',
         'Cell: EdUrawINT (DDD-bckgrnd)': 'edu',
         'Cell: EdUbackground (DDD-bckgrnd)': 'edu_bg',
        'Cell: HoechstINT (DDD-bckgrnd)': 'dna'
        }
y = mg.update_ldr_gating(obj, well, ndict, plot_with_dna = True, is_ldrint = True, is_csv=True)
display(y)


peak_locs
[ 26 118 138]
cc
[-1.06529668  1.99779776  2.66368785]


/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:246: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:104: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:153: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:321: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)


interactive(children=(FloatSlider(value=1.9977977597619816, description='ldr_cutoff', max=4.087838049488207, m…

In [30]:
z = mg.update_gating(obj, well, ndict, is_ldrint = True, is_csv=True, ph3_channel=False)
display(z)

peak_locs
[]
cc
[]


/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:246: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:104: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:153: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)
/mnt/c/Users/NC168/git/DrugResponse/python/cell_cycle_gating/dead_cell_filter_ldrint.py:321: RuntimeWarning: invalid value encountered in log10
  logint = np.log10(ldrint)


interactive(children=(FloatSlider(value=3.1536505443837433, description='g1_left', max=4.209360656120261, min=…

In [ ]:
dfo = pd.read_csv(obj)
#dfo.sort_values(by=['ldrint'], ascending = False)

In [ ]:
f

In [ ]:
np.sum(np.isnan(dfo.ldrint))

In [ ]:
plt.hist(np.log10(dfo.ldrint))

In [ ]:
np.arange(0, dfo.ldrint.max(), 100)